// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIDs
{
        public const string achievement_im_all_yours_baby = "CgkImsLKle4UEAIQDQ"; // <GPGSID>
        public const string achievement_its_starting_to_be_an_obssession = "CgkImsLKle4UEAIQCw"; // <GPGSID>
        public const string achievement_you_must_be_into_me = "CgkImsLKle4UEAIQCg"; // <GPGSID>
        public const string achievement_conquered_the_mountain = "CgkImsLKle4UEAIQBg"; // <GPGSID>
        public const string achievement_first_step = "CgkImsLKle4UEAIQAg"; // <GPGSID>
        public const string achievement_reached_500m = "CgkImsLKle4UEAIQBQ"; // <GPGSID>
        public const string leaderboard_best_workers_times_played = "CgkImsLKle4UEAIQBw"; // <GPGSID>
        public const string achievement_be_careful_of_what_you_wish_for = "CgkImsLKle4UEAIQDA"; // <GPGSID>
        public const string achievement_reached_100m = "CgkImsLKle4UEAIQAw"; // <GPGSID>
        public const string achievement_reached_250m = "CgkImsLKle4UEAIQBA"; // <GPGSID>
        public const string achievement_are_you_starting_to_like_me = "CgkImsLKle4UEAIQCQ"; // <GPGSID>
        public const string achievement_hi_nice_to_meet_you = "CgkImsLKle4UEAIQCA"; // <GPGSID>
        public const string leaderboard_best_players_highscores = "CgkImsLKle4UEAIQAA"; // <GPGSID>

}

